---
functional:
  - Регистрация и аутентификация пользователей
  - Создание, управление и участие в игре
  - Возможность просмотра рейтингов и достижений других участников
  - Возможность создания задач разного уровня сложности
  - Учёт и отображение времени, затраченного на решение каждой задачи
  - Обратная связь об успешном или неуспешном решении задачи
  - Поддержка чата для пользователей
non-functional:
  - Интуитивно понятная навигация по сайту
  - Оптимальное расположение элементов и удобное отображение
  - Поддержка различных устройств и браузеров
  - Защита персональных данных пользователей
  - Защита от взлома
  - Безопасноый вход и хранения паролей
  - Адаптивный дизайн для удобной работы на мобильных устройствах
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Быстрый отклик при выполнении действий пользователей
implicit:
  - Сайт должен поддерживать несколько языков
  - Разграничения прав доступа в системе
